# Generated by Django 2.2.4 on 2019-08-18 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyitem',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
