# Generated by Django 2.2.4 on 2019-08-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_scrapyitem_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyitem',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
