# Generated by Django 2.2.4 on 2019-08-19 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_scrapyitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapyitem',
            name='unique_id',
        ),
    ]
