# Generated by Django 2.2.4 on 2019-08-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_scrapyitem_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyitem',
            name='recommends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapyitem',
            name='unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scrapyitem',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
