# Generated by Django 2.2.4 on 2019-08-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190820_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyitem',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
